name: Build Docker Image

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_VER: 89-1.2
  USERNAME: ${{ vars.USERNAME }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment:
      name: prod
    
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 1

      - name: Set up Docker Buildx
        timeout-minutes: 1
        uses: docker/setup-buildx-action@v3


      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      
      - name: Test
        run: |
          docker run --rm test text-embeddings-router --help

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: choronz/text-embeddings-inference:$IMAGE_VER

