name: Build Docker Image

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  packages: write

env:
  USERNAME: ${{ vars.USERNAME }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment:
      name: prod
    
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 1

      - name: Set up Docker Buildx
        timeout-minutes: 1
        uses: docker/setup-buildx-action@v3


      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:89-1.2

